# Generated by Django 4.2.16 on 2026-03-27 11:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CrawlerTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='任务名称')),
                ('task_type', models.CharField(choices=[('university', '院校信息'), ('score', '分数线'), ('plan', '招生计划'), ('major', '专业信息')], max_length=20, verbose_name='任务类型')),
                ('target_url', models.URLField(blank=True, default='', verbose_name='目标地址')),
                ('status', models.CharField(choices=[('pending', '等待中'), ('running', '运行中'), ('success', '成功'), ('failed', '失败')], default='pending', max_length=10, verbose_name='状态')),
                ('total_count', models.IntegerField(default=0, verbose_name='总数据量')),
                ('success_count', models.IntegerField(default=0, verbose_name='成功数量')),
                ('fail_count', models.IntegerField(default=0, verbose_name='失败数量')),
                ('log', models.TextField(blank=True, default='', verbose_name='运行日志')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='开始时间')),
                ('finished_at', models.DateTimeField(blank=True, null=True, verbose_name='完成时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '爬虫任务',
                'verbose_name_plural': '爬虫任务',
                'db_table': 'crawler_tasks',
            },
        ),
        migrations.CreateModel(
            name='CrawlerData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_type', models.CharField(max_length=20, verbose_name='数据类型')),
                ('raw_data', models.JSONField(verbose_name='原始数据')),
                ('is_cleaned', models.BooleanField(default=False, verbose_name='是否已清洗')),
                ('cleaned_data', models.JSONField(blank=True, null=True, verbose_name='清洗后数据')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='data_items', to='crawler.crawlertask', verbose_name='所属任务')),
            ],
            options={
                'verbose_name': '爬取数据',
                'verbose_name_plural': '爬取数据',
                'db_table': 'crawler_data',
            },
        ),
    ]
