# Generated by Django 4.2.16 on 2026-03-27 11:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='University',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='院校名称')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='院校代码')),
                ('province', models.CharField(max_length=20, verbose_name='所在省份')),
                ('city', models.CharField(max_length=30, verbose_name='所在城市')),
                ('level', models.CharField(max_length=20, verbose_name='办学层次')),
                ('type', models.CharField(max_length=20, verbose_name='院校类型')),
                ('is_985', models.BooleanField(default=False, verbose_name='985院校')),
                ('is_211', models.BooleanField(default=False, verbose_name='211院校')),
                ('is_double_first', models.BooleanField(default=False, verbose_name='双一流')),
                ('website', models.URLField(blank=True, default='', verbose_name='官网')),
                ('description', models.TextField(blank=True, default='', verbose_name='简介')),
                ('ranking', models.IntegerField(blank=True, null=True, verbose_name='排名')),
                ('employment_rate', models.DecimalField(decimal_places=2, max_digits=5, null=True, verbose_name='就业率')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='university_logos/', verbose_name='校徽')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '院校',
                'verbose_name_plural': '院校',
                'db_table': 'universities',
            },
        ),
        migrations.CreateModel(
            name='Major',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='专业名称')),
                ('code', models.CharField(max_length=20, verbose_name='专业代码')),
                ('category', models.CharField(max_length=30, verbose_name='学科门类')),
                ('duration', models.IntegerField(default=4, verbose_name='学制')),
                ('degree', models.CharField(default='', max_length=30, verbose_name='授予学位')),
                ('description', models.TextField(blank=True, default='', verbose_name='专业简介')),
                ('employment_rate', models.DecimalField(decimal_places=2, max_digits=5, null=True, verbose_name='就业率')),
                ('avg_salary', models.IntegerField(blank=True, null=True, verbose_name='平均薪资')),
                ('university', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='majors', to='universities.university', verbose_name='所属院校')),
            ],
            options={
                'verbose_name': '专业',
                'verbose_name_plural': '专业',
                'db_table': 'majors',
            },
        ),
        migrations.CreateModel(
            name='EnrollmentPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(verbose_name='年份')),
                ('province', models.CharField(max_length=20, verbose_name='招生省份')),
                ('subject_type', models.CharField(max_length=10, verbose_name='科类')),
                ('plan_count', models.IntegerField(verbose_name='计划人数')),
                ('tuition', models.IntegerField(blank=True, null=True, verbose_name='学费(元/年)')),
                ('remark', models.TextField(blank=True, default='', verbose_name='备注')),
                ('major', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='plans', to='universities.major', verbose_name='专业')),
                ('university', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plans', to='universities.university', verbose_name='院校')),
            ],
            options={
                'verbose_name': '招生计划',
                'verbose_name_plural': '招生计划',
                'db_table': 'enrollment_plans',
            },
        ),
        migrations.CreateModel(
            name='AdmissionScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(verbose_name='年份')),
                ('province', models.CharField(max_length=20, verbose_name='招生省份')),
                ('subject_type', models.CharField(max_length=10, verbose_name='科类')),
                ('batch', models.CharField(max_length=20, verbose_name='批次')),
                ('min_score', models.IntegerField(verbose_name='最低分')),
                ('max_score', models.IntegerField(blank=True, null=True, verbose_name='最高分')),
                ('avg_score', models.IntegerField(blank=True, null=True, verbose_name='平均分')),
                ('min_rank', models.IntegerField(blank=True, null=True, verbose_name='最低位次')),
                ('plan_count', models.IntegerField(blank=True, null=True, verbose_name='招生计划数')),
                ('actual_count', models.IntegerField(blank=True, null=True, verbose_name='实际录取数')),
                ('major', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='scores', to='universities.major', verbose_name='专业')),
                ('university', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scores', to='universities.university', verbose_name='院校')),
            ],
            options={
                'verbose_name': '录取分数线',
                'verbose_name_plural': '录取分数线',
                'db_table': 'admission_scores',
            },
        ),
    ]
