# Generated by Django 6.0.4 on 2026-04-22 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('universities', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='major',
            name='major_group',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='专业组/选科要求'),
        ),
        migrations.AddField(
            model_name='major',
            name='tuition',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='学费'),
        ),
        migrations.AlterUniqueTogether(
            name='admissionscore',
            unique_together={('university', 'major', 'year', 'province', 'batch', 'subject_type')},
        ),
    ]
