# Generated by Django 6.0.4 on 2026-04-22 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('universities', '0002_major_major_group_major_tuition_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='StandardMajor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('special_id', models.CharField(max_length=20, unique=True, verbose_name='平台专业ID')),
                ('code', models.CharField(blank=True, max_length=20, null=True, verbose_name='专业代码')),
                ('name', models.CharField(max_length=100, verbose_name='专业名称')),
                ('level1_name', models.CharField(blank=True, max_length=50, null=True, verbose_name='学历层次')),
                ('level2_name', models.CharField(blank=True, max_length=50, null=True, verbose_name='学科门类')),
                ('level3_name', models.CharField(blank=True, max_length=50, null=True, verbose_name='专业类')),
                ('degree', models.CharField(blank=True, max_length=50, null=True, verbose_name='授予学位')),
                ('years', models.CharField(blank=True, max_length=20, null=True, verbose_name='修业年限')),
                ('salary_avg', models.IntegerField(blank=True, null=True, verbose_name='全国平均起薪')),
                ('salary_5year', models.IntegerField(blank=True, null=True, verbose_name='5年后平均薪资')),
                ('boy_rate', models.IntegerField(blank=True, null=True, verbose_name='男生比例(%)')),
                ('girl_rate', models.IntegerField(blank=True, null=True, verbose_name='女生比例(%)')),
            ],
            options={
                'verbose_name': '国家标准专业',
                'verbose_name_plural': '国家标准专业',
            },
        ),
    ]
