# Generated by Django 4.2.16 on 2026-03-27 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DataPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(max_length=20, verbose_name='角色')),
                ('module', models.CharField(max_length=50, verbose_name='模块')),
                ('can_view', models.BooleanField(default=True, verbose_name='可查看')),
                ('can_edit', models.BooleanField(default=False, verbose_name='可编辑')),
                ('can_delete', models.BooleanField(default=False, verbose_name='可删除')),
                ('can_export', models.BooleanField(default=False, verbose_name='可导出')),
                ('data_scope', models.CharField(default='all', max_length=50, verbose_name='数据范围')),
                ('remark', models.TextField(blank=True, default='', verbose_name='备注')),
            ],
            options={
                'verbose_name': '数据权限',
                'verbose_name_plural': '数据权限',
                'db_table': 'data_permissions',
            },
        ),
        migrations.CreateModel(
            name='ModelTrainLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='模型名称')),
                ('status', models.CharField(choices=[('pending', '等待中'), ('training', '训练中'), ('success', '训练完成'), ('failed', '训练失败')], default='pending', max_length=10, verbose_name='状态')),
                ('data_count', models.IntegerField(default=0, verbose_name='训练数据量')),
                ('accuracy', models.DecimalField(decimal_places=2, max_digits=5, null=True, verbose_name='准确率')),
                ('params', models.JSONField(blank=True, null=True, verbose_name='训练参数')),
                ('log', models.TextField(blank=True, default='', verbose_name='训练日志')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='开始时间')),
                ('finished_at', models.DateTimeField(blank=True, null=True, verbose_name='完成时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '模型训练日志',
                'verbose_name_plural': '模型训练日志',
                'db_table': 'model_train_logs',
            },
        ),
        migrations.CreateModel(
            name='OperationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50, verbose_name='用户名')),
                ('action', models.CharField(max_length=50, verbose_name='操作类型')),
                ('module', models.CharField(max_length=50, verbose_name='操作模块')),
                ('detail', models.TextField(blank=True, default='', verbose_name='操作详情')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP地址')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='操作时间')),
            ],
            options={
                'verbose_name': '操作日志',
                'verbose_name_plural': '操作日志',
                'db_table': 'operation_logs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SystemConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=50, unique=True, verbose_name='配置键')),
                ('value', models.TextField(verbose_name='配置值')),
                ('description', models.CharField(blank=True, default='', max_length=200, verbose_name='说明')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '系统配置',
                'verbose_name_plural': '系统配置',
                'db_table': 'system_configs',
            },
        ),
    ]
