# Generated by Django 4.2.16 on 2026-03-27 11:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('universities', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VolunteerForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='志愿表名称')),
                ('score', models.IntegerField(verbose_name='高考分数')),
                ('province', models.CharField(max_length=20, verbose_name='省份')),
                ('subject_type', models.CharField(max_length=10, verbose_name='科类')),
                ('status', models.CharField(choices=[('draft', '草稿'), ('submitted', '已提交'), ('analyzed', '已分析')], default='draft', max_length=10, verbose_name='状态')),
                ('analysis', models.TextField(blank=True, default='', verbose_name='分析结果')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='volunteer_forms', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '志愿表',
                'verbose_name_plural': '志愿表',
                'db_table': 'volunteer_forms',
            },
        ),
        migrations.CreateModel(
            name='VolunteerItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField(verbose_name='志愿序号')),
                ('level', models.CharField(blank=True, default='', max_length=10, verbose_name='冲稳保')),
                ('probability', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='录取概率')),
                ('form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='volunteer.volunteerform', verbose_name='志愿表')),
                ('major', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='universities.major', verbose_name='专业')),
                ('university', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='universities.university', verbose_name='院校')),
            ],
            options={
                'verbose_name': '志愿项',
                'verbose_name_plural': '志愿项',
                'db_table': 'volunteer_items',
                'ordering': ['order'],
            },
        ),
    ]
