# Generated by Django 4.2.16 on 2026-03-27 11:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('universities', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssessmentQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='题目内容')),
                ('option_a', models.CharField(max_length=200, verbose_name='选项A')),
                ('option_b', models.CharField(max_length=200, verbose_name='选项B')),
                ('option_c', models.CharField(max_length=200, verbose_name='选项C')),
                ('option_d', models.CharField(max_length=200, verbose_name='选项D')),
                ('category', models.CharField(max_length=30, verbose_name='测评维度')),
                ('order', models.IntegerField(default=0, verbose_name='排序')),
            ],
            options={
                'verbose_name': '测评题目',
                'verbose_name_plural': '测评题目',
                'db_table': 'assessment_questions',
            },
        ),
        migrations.CreateModel(
            name='AssessmentResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answers', models.JSONField(verbose_name='答题记录')),
                ('result', models.JSONField(verbose_name='测评结果')),
                ('recommended_majors', models.TextField(verbose_name='推荐专业方向')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='测评时间')),
            ],
            options={
                'verbose_name': '测评结果',
                'verbose_name_plural': '测评结果',
                'db_table': 'assessment_results',
            },
        ),
        migrations.CreateModel(
            name='RecommendRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(choices=[('rush', '冲'), ('stable', '稳'), ('safe', '保')], max_length=10, verbose_name='推荐等级')),
                ('score', models.IntegerField(verbose_name='用户分数')),
                ('probability', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='录取概率')),
                ('reason', models.TextField(blank=True, default='', verbose_name='推荐理由')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='推荐时间')),
                ('major', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='universities.major', verbose_name='推荐专业')),
                ('university', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='universities.university', verbose_name='推荐院校')),
            ],
            options={
                'verbose_name': '推荐记录',
                'verbose_name_plural': '推荐记录',
                'db_table': 'recommend_records',
            },
        ),
    ]
